# -*- coding: utf-8 -*-
"""lottory.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U9KOsaKZN-1p2SQTiM40I-xqE_2i8Kc1
"""

import random

phone_numbers = []

"""**Getting the number of participants**"""

Participant = int(input('Enter the number of participants: '))

for i in range(Participant):
    pre = '09'
    numbers = random.randint(100_000_000, 999_999_999)
    phone_number = f'{pre}{numbers}'
    phone_numbers.append(phone_number)

"""**Getting the number of winners**"""

Winner = int(input('Enter the number of winners: '))

winners = random.sample(phone_numbers, Winner)

"""**Getting the number of winners**"""

winners = [item[:4]+'***'+item[-3:] for item in winners]

print('The winner is:', winners)



"""# New Section"""