# -*- coding: utf-8 -*-
"""Function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18iBAcEdXLdtHj6eS0lgmFwKSUuJL2a5f
"""

import numpy as np
import matplotlib.pyplot as plt

def plot_normal_dist (n):
    return np.random.normal(loc=0, scale=1, size=n)

data = plot_normal_dist(10)
plt.figure()
plt.hist(data, bins=100, density=True, alpha=0.6, color='b')
plt.xlabel('value')
plt.ylabel('frequency')
plt.title('Normal Distribution ( n=10 mean=0 , std=1)')
plt.show()

data = plot_normal_dist(1000)
plt.figure()
plt.hist(data, bins=100, density=True, alpha=0.6, color='r')
plt.xlabel('value')
plt.ylabel('frequency')
plt.title('Normal Distribution ( n=10 mean=0 , std=1)')
plt.show()

data = plot_normal_dist(100000)
plt.figure()
plt.hist(data, bins=100, density=True, alpha=0.6, color='g')
plt.xlabel('value')
plt.ylabel('frequency')
plt.title('Normal Distribution ( n=10 mean=0 , std=1)')
plt.show()