# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GZvCyAiakEl_oVzN2yHbPYkkX_-SaVIx
"""

import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(-5, 5, 500)

"""Display the function x^3"""

y1 = (x**3)
plt.figure()
plt.plot(x, y1 , 'k--')
plt.fill_between(x, y1, color='gray', alpha=0.5)
plt.title ('plot of x^3')
plt.xlabel('x')
plt.ylabel('f(x)')
plt.legend()
plt.show()

"""Display the functions exp(-x^2) & cos(1.2x)"""

y2 = np.cos(1.2 * x)
y3 = np.exp(-(x**2))
plt.figure()
plt.plot(x, y2 , 'b-.' , label = 'cos(1.2x)')
plt.plot(x , y3 , 'm' , label = 'exp(-x^2)')
plt.title ('plot of exp(-x^2) & cos(1.2x)')
plt.xlabel('x')
plt.ylabel('f(x)')
plt.legend()
plt.show()

